BTL_VTJob/Controllers/BaiTuyenDungController.cs
using BTL_VTJob.Data;
using BTL_VTJob.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;

namespace BTL_VTJob.Controllers
{
    public class BaiTuyenDungController : Controller
    {
        private readonly ILogger<BaiTuyenDungController> _logger;
        private readonly dbContext _context;

        public BaiTuyenDungController(ILogger<BaiTuyenDungController> logger ,dbContext context)
        {
            _logger = logger;
            _context=context;
        }
        // GET: BaiUngTuyenController

        public async Task<IActionResult> GetList()
        {
            /* string userID = HttpContext.Session.GetString("Email");
             var user = _context.Nguoidung.Where(u=>u.Email==userID);
             if(user != null)
             {
               */
            string email = HttpContext.Session.GetString("Email");

            var user = await _context.Nguoidung.Where(u => u.Email == email).FirstOrDefaultAsync();
            var doanhNghiep = await _context.DoanhNghiep.Where(u => u.UserID == user.UserID).FirstOrDefaultAsync();

            var list = _context.BaiTuyenDung.Where(u=>u.IdDoanhNghiep==doanhNghiep.Id).Include(p => p.DoanhNghiep).Include(p => p.LoaiCongViec);
           
                return View(await list.ToListAsync());
           /* }
            * 
            return Redirect("/home");*/
            
        }
        
        public IActionResult CreateBaiTuyenDung()
        {
           

            
            return View(new BaiTuyenDung());

        }
      
        [HttpPost]
        public async Task<IActionResult> CreateBaiTuyenDung(BaiTuyenDung baiTuyenDung)
        {
            string email = HttpContext.Session.GetString("Email");
            var user = await _context.Nguoidung.Where(u => u.Email == email).FirstOrDefaultAsync();
            var doanhNghiep = await _context.DoanhNghiep.Where(u => u.UserID == user.UserID).FirstOrDefaultAsync();

            baiTuyenDung.IdDoanhNghiep =doanhNghiep.Id ;
            /*var loaiJob= await _context.LoaiJob.Where(u => u.Id== baiTuyenDung.LoaiCongViec.Id).FirstOrDefaultAsync();*/
            baiTuyenDung.LoaiCongViec = baiTuyenDung.LoaiCongViec;
            baiTuyenDung.DoanhNghiep = doanhNghiep;
            baiTuyenDung.NgayDang = DateTime.Now;
            _context.BaiTuyenDung.Add(baiTuyenDung);
            _context.SaveChanges();
          return Redirect("GetList"); ;

        }
        public async Task<IActionResult> GetDSLoaiJob()
        {
             // Kết nối và truy vấn dữ liệu từ cơ sở dữ liệu
                var dsLoaiJob = _context.LoaiJob.ToList();
                // Trả về danh sách các mục cho dropdownlist dưới dạng JSON
                return Json(dsLoaiJob);

        }
      
        [HttpGet]
        public async Task<IActionResult> UpdateBaiTuyenDung(string id)
        {
            var baiTuyenDung= _context.BaiTuyenDung.Where(p=>p.MaBai==id).Include(p => p.DoanhNghiep).Include(p => p.LoaiCongViec).FirstOrDefault();
         


            return View(baiTuyenDung);

        }
        [HttpPost]
        public async Task<IActionResult> UpdateBaiTuyenDung(BaiTuyenDung baiTuyenDung)
        {

            var bai = await _context.BaiTuyenDung.Where(u => u.MaBai == baiTuyenDung.MaBai).FirstOrDefaultAsync();
            /* var user = await _context.Nguoidung.Where(u => u.UserID == bai.UserID).FirstOrDefaultAsync();   
             baiTuyenDung.UserID = bai.UserID;
             baiTuyenDung.NguoiDung = user;*/
            var job  = await _context.LoaiJob.Where(u => u.Id == baiTuyenDung.IdLoaiJob).FirstOrDefaultAsync();
            bai.MoTaCV = baiTuyenDung.MoTaCV;
            bai.SoLuongTuyen = baiTuyenDung.SoLuongTuyen;
            bai.MucLuong = baiTuyenDung.MucLuong;
            bai.QuyenLoi = baiTuyenDung.QuyenLoi;
            bai.YeuCau = baiTuyenDung.YeuCau;
            bai.TieuDe = baiTuyenDung.TieuDe;
            bai.HanNopCV = baiTuyenDung.HanNopCV;
            bai.LoaiCongViec = job;
            bai.IdLoaiJob = baiTuyenDung.IdLoaiJob;
            _context.BaiTuyenDung.Update(bai);
            _context.SaveChanges();
            return Redirect("GetList");
        }
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var bai = await _context.BaiTuyenDung.Where(u => u.MaBai == id).FirstOrDefaultAsync();
            _context.BaiTuyenDung.Remove(bai);
            _context.SaveChanges();
            return Redirect("GetList");

        }

        public async Task<IActionResult> DetailJob(string id)
        {
            var detaiJob=_context.BaiTuyenDung.Where(u=>u.MaBai == id).Include(p=>p.DoanhNghiep).Include(p => p.LoaiCongViec).FirstOrDefault();
            /*var user = await _context.Nguoidung.Where(u => u.UserID == detaiJob.UserID).FirstOrDefaultAsync();
            var doanhNghiep = await _context.DoanhNghiep.Where(u => u.UserID == user.UserID).FirstOrDefaultAsync();
            ViewBag.Anh = doanhNghiep.Anh;
            ViewBag.ThongTinDN = doanhNghiep.MoTa;
            ViewBag.TenDN = doanhNghiep.TenCT;
            ViewBag.DiaChi = doanhNghiep.DiaChi;*/

            return View(detaiJob);

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BTL_VTJob/Controllers/NguoiDungController.cs
using BTL_VTJob.Data;
using BTL_VTJob.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace BTL_VTJob.Controllers
{
    public class NguoiDungController : Controller
    {
        private readonly ILogger<NguoiDungController> _logger;
         private readonly dbContext _context;

        public NguoiDungController(ILogger<NguoiDungController> logger ,dbContext context)
        {
            _logger = logger;
            _context=context;
        }
        public async Task<IActionResult> GetDoanhNghiep()
        {
            var list = _context.DoanhNghiep.Include(p => p.NguoiDung);
            return View(await list.ToListAsync());

        }
        public async Task<IActionResult> GetListUser()
        {
            var list = await _context.Nguoidung.ToListAsync();
            return View( list);

        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BTL_VTJob/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    @*<meta name="viewport" content="width=device-width, initial-scale=1.0" />*@
    <title>@ViewData["Title"] - BTL_VTJob</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="/BTL_VTJob.styles.css" asp-append-version="true" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
        <link rel="shortcut icon" href="ftco-32x32.png">
    <link rel="stylesheet" href="~/css/quill.snow.css">
    <link rel="stylesheet" href="~/fonts/icomoon/style.css">
    <link rel="stylesheet" href="~/fonts/line-icons/style.css">
    <link rel="stylesheet" href="~/css/jquery.fancybox.min.css">

    <link rel="stylesheet" href="~/css/custom-bs.css">
    <link rel="stylesheet" href="~/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/animate.min.css">
    <link href="~/lib/fontawesome-free-5.15.4-web/fontawesome-free-5.15.4-web/css/all.css" rel="stylesheet" />
    <link href="~/lib/fontawesome-free-5.15.4-web/fontawesome-free-5.15.4-web/css/all.min.css" rel="stylesheet" />

        <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/css/style.css">
   
</head>
<body id="top">
 
    <div class="site-wrap">

       

    <header class="site-navbar mt-3">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="site-logo col-3"><a href="index.html">VTJob</a></div>

                    <nav class="mx-auto col-6 site-navigation text-center">
                    <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
                                <li> <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Trang chủ</a></li>
                            @if (Context.Session.Keys.Contains("Email"))
                            {
                                @if (@Context.Session.GetString("Quyen") == "Admin")
                                {
                                    <li class="has-children">
                                        <a href="job-listings.html">Admin</a>
                                        <ul class="dropdown">
                                            <li><a class="nav-link text-dark" asp-area="" asp-controller="NguoiDung" asp-action="GetListUser">Người dùng</a></li>
                                            <li><a class="nav-link text-dark" asp-area="" asp-controller="NguoiDung" asp-action="GetDoanhNghiep">Doanh nghiệp</a></li>

                                        </ul>
                                    </li>
                                }
                                @if (@Context.Session.GetString("Quyen") == "Management")
                                {
                                    <li class="has-children">
                                        <a href="job-listings.html">Doanh Nghiệp</a>
                                        <ul class="dropdown">
                                            <a class="nav-link" asp-area="" asp-controller="BaiTuyenDung" asp-action="GetList">Danh sách Job</a>
                                            <li><a class="nav-link text-dark" asp-area="" asp-controller="BaiTuyenDung" asp-action="CreateBaiTuyenDung">Tạo job</a></li>
                                        </ul>
                                    </li>

                                }
                               
                            }       
                        <li class="d-lg-none"><a asp-area="" asp-controller="DangKy" asp-action="register"> Đăng Ký</a> </li>
                    </ul>
                </nav>
                    </div>
                <div class="right-cta-menu justify-content-end text-right d-flex  col-3">
                    <div class="ml-auto">
                        @if(Context.Session.Keys.Contains("Email")) {
                            <p>@Context.Session.GetString("HoTen") </p>
                            <a asp-area="" asp-controller="Dangky" asp-action="Logout" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>Log out</a>

                        }else{
                            <a asp-area="" asp-controller="Dangky" asp-action="register" class="btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-add"></span>Register</a>
                            <a asp-area="" asp-controller="DangKy" asp-action="login" class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span class="mr-2 icon-lock_outline"></span>Log In</a>
                        }
                        
                    </div>
                    <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span class="icon-menu h3 m-0 p-0 mt-2"></span></a>
                </div>

        </div>
    </header>
        <section class="section-hero inner-page overlay bg-image" style="background-image: url('/images/hero_1.jpg');" id="home-section">

            <div class="container">
                <div class="row align-items-center justify-content-center">
                    <div class="col-md-12">
                        <div class="mb-5 text-center">
                            <h1 class="text-white font-weight-bold">The Easiest Way To Get Your Dream Job</h1>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cupiditate est, consequuntur perferendis.</p>
                        </div>
                       
                    </div>
                </div>
            </div>

    </section>

        <section class="site-section">
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
        </section>


    <footer class="site-footer">

       

        <div class="container">
            <div class="row mb-5">
                <div class="col-6 col-md-3 mb-4 mb-md-0">
                    <h3>Search Trending</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Web Design</a></li>
                        <li><a href="#">Graphic Design</a></li>
                        <li><a href="#">Web Developers</a></li>
                        <li><a href="#">Python</a></li>
                        <li><a href="#">HTML5</a></li>
                        <li><a href="#">CSS3</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md-3 mb-4 mb-md-0">
                    <h3>Company</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Career</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Resources</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md-3 mb-4 mb-md-0">
                    <h3>Support</h3>
                    <ul class="list-unstyled">
                        <li><a href="#">Support</a></li>
                        <li><a href="#">Privacy</a></li>
                        <li><a href="#">Terms of Service</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md-3 mb-4 mb-md-0">
                    <h3>Contact Us</h3>
                    <div class="footer-social">
                        <a href="#"><span class="icon-facebook"></span></a>
                        <a href="#"><span class="icon-twitter"></span></a>
                        <a href="#"><span class="icon-instagram"></span></a>
                        <a href="#"><span class="icon-linkedin"></span></a>
                    </div>
                </div>
            </div>

            <div class="row text-center">
                <div class="col-12">
                    <p class="copyright">
                        <small>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy;
                            <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made
                            with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com"
                                                                                                 target="_blank">Colorlib</a>
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </small>
                    </p>
                </div>
            </div>
        </div>
    </footer>

    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/quill.min.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/js/isotope.pkgd.min.js"></script>
    <script src="~/js/stickyfill.min.js"></script>
    <script src="~/js/jquery.fancybox.min.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/bootstrap-select.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>